pnpm detection added in github action file

diff --git a/.github/workflows/Project_Deployment.yml b/.github/workflows/Project_Deployment.yml
--- a/.github/workflows/Project_Deployment.yml
+++ b/.github/workflows/Project_Deployment.yml
@@ -24,8 +24,8 @@ env:
   BUILD_PATH: "."
   AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-  AWS_DEFAULT_REGION: eu-west-3  # replace with your AWS region
-  CLOUDFRONT_DISTRIBUTION_ID: E12J3TXUPCBX6Q  # replace with your CloudFront distribution ID
+  AWS_DEFAULT_REGION: eu-west-3 # replace with your AWS region
+  CLOUDFRONT_DISTRIBUTION_ID: E12J3TXUPCBX6Q # replace with your CloudFront distribution ID
 
 jobs:
   build:
@@ -37,20 +37,26 @@ jobs:
       - name: Detect package manager
         id: detect-package-manager
         run: |
-          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
-            echo "manager=yarn" >> $GITHUB_OUTPUT
-            echo "command=install" >> $GITHUB_OUTPUT
-            echo "runner=yarn" >> $GITHUB_OUTPUT
-            exit 0
-          elif [ -f "${{ github.workspace }}/package.json" ]; then
-            echo "manager=npm" >> $GITHUB_OUTPUT
-            echo "command=ci" >> $GITHUB_OUTPUT
-            echo "runner=npx --no-install" >> $GITHUB_OUTPUT
-            exit 0
-          else
-            echo "Unable to determine package manager"
-            exit 1
-          fi
+            if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+                echo "manager=yarn" >> $GITHUB_OUTPUT
+                echo "command=install" >> $GITHUB_OUTPUT
+                echo "runner=yarn" >> $GITHUB_OUTPUT
+                exit 0
+            elif [ -f "${{ github.workspace }}/package-lock.json" ]; then
+                echo "manager=npm" >> $GITHUB_OUTPUT
+                echo "command=ci" >> $GITHUB_OUTPUT
+                echo "runner=npx --no-install" >> $GITHUB_OUTPUT
+                exit 0
+            elif [ -f "${{ github.workspace }}/pnpm-lock.yaml" ]; then
+                echo "manager=pnpm" >> $GITHUB_OUTPUT
+                echo "command=install" >> $GITHUB_OUTPUT
+                echo "runner=pnpm" >> $GITHUB_OUTPUT
+                exit 0
+            else
+                echo "Unable to determine package manager"
+                exit 1
+            fi
+
       - name: Setup Node
         uses: actions/setup-node@v3
         with:
@@ -59,22 +65,22 @@ jobs:
           cache-dependency-path: ${{ env.BUILD_PATH }}/package-lock.json
 
       - name: Install dependencies
-        run: npm ci && npm fund
+        run: pnpm install
 
       - name: Let Vite.js build static files
         run: npm run build
-      
+
       - name: End Message
         run: echo "Build successfull"
       - name: Install AWS CLI
         run: |
-            sudo apt-get update
-            sudo apt-get install -y awscli
-      
+          sudo apt-get update
+          sudo apt-get install -y awscli
+
       - name: Push build files to S3
         run: |
           aws s3 cp dist s3://jlerocher.pro/flashCards --recursive
-      
+
       - name: Invalidate CloudFront Cache
         run: |
           aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
